# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gUTYfZ2JLelWQFBpowq0-vW_zHrdm1XD
"""

from pyspark.context import SparkContext,SparkConf

#Establecemos un nombre para la aplicación y Indicamos que se ejecutara de manera Local
conf = SparkConf().setAppName("ContarPalabras").setMaster("local")
sc = SparkContext(conf=conf)

#Leemos el archivo en la ruta que hemos especificado
archivo = sc.textFile("/Descargas/archivo.txt")

#Tranformacion FlatMap toma cada línea del archivo, la divide en palabras utilizando el espacio como delimitador
palabras = archivo.flatMap(lambda linea: linea.split(" "))
palabras_contadas = palabras.map(lambda palabra: (palabra, 1)).reduceByKey(lambda a, b: a + b)

for palabra, conteo in palabras_contadas.collect():
    print(f"{palabra}: {conteo}")